export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const INCREASE_ITEMS = "INCREASE_ITEMS";
export const DECREASE_ITEMS = "DECREASE_ITEMS";

export const FILTER_BY_TAG = "FILTER_BY_TAG";
export const FILTER_BY_ITEM_TYPE = "FILTER_BY_ITEM_TYPE";
export const FILTER_BY_BRAND = "FILTER_BY_BRAND";
export const SORTING_BY_PRICE = "SORTING_BY_PRICE";
export const SORTING_BY_TIME = "SORTING_BY_TIME";

export const FETCHING_PRODUCTS = "FETCHING_PRODUCTS";
export const FETCHING_COMPANIES = "FETCHING_COMPANIES";
